\documentclass[12pt]{article}
\usepackage{fixltx2e}

\setlength{\parindent}{0.0in}
\setlength{\parskip}{0.125in}


\begin{document}
\begin{itemize}
	\item This is a test with \textbf{Bold} text inside.

	\item This is a test with <b>\textit{Bold and Italic}</b> text inside.

	\item This is a <!-- Bet you didn't see this one coming \textbf{right?} --> test with a comment inside of it!

\end{itemize}
\end{document}
