\documentclass[12pt]{article}
\usepackage{fixltx2e}

\setlength{\parindent}{0.0in}
\setlength{\parskip}{0.125in}


\begin{document}
\section{Primary Header}This is some large introductory text.

This is some small introductory text.

This is some bold introductory text.

This is some italics introductory text.

This is some emphasized introductory text.

This is some strong introductory text.

This is the 7th paragraph

This is the 8th paragraph

\end{document}
