\documentclass[12pt]{article}
\usepackage{fixltx2e}

\setlength{\parindent}{0.0in}
\setlength{\parskip}{0.125in}


\begin{document}
\section{Primary Header}This is some {\Large large introductory} text.

This is some {\scriptsize small introductory} text.

This is some \textbf{bold introductory} text.

This is some \textit{italics introductory} text.

This is some \emph{emphasized introductory} text.

This is some \textmd{strong introductory} text.

This is the 7\textsuperscript{th} paragraph

This is the 8\textsubscript{th} paragraph

\subsection{Secondary Header}\end{document}
